version: "4"
services:
  front:
    container_name: front
    image: front
    ports:
      - "5001:5001"
    build: "../Front-End"
    depends_on: 
      - backend
    
  backend:
    container_name: backend
    image: backend
    ports: 
      - "3005:3005"
    build: "."
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"